//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FDMS.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define ID_EDIT_TOGGLE                  5
#define ID_EDIT_TOGGLE2                 6
#define ID_DEL_SEL_M                    6
#define ID_ADD_NEW_M                    7
#define ID_EDIT_TOGGLE3                 8
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_FDMSTYPE                    129
#define IDD_DIALOG_MEASURE              130
#define IDD_DIALOG_ALLOTHER             131
#define IDD_DIALOG_HELP                 133
#define IDD_DOASSAY                     134
#define IDD_DIALOG2                     135
#define IDD_DIALOG1                     136
#define IDACK                           137
#define IDD_DIALOG_ACCEPT               137
#define IDD_DIALOG3                     138
#define IDD_DIALOG_QUIT                 139
#define IDD_DIALOG_NEWMEASURE           140
#define IDB_BMP_ALL                     142
#define IDD_DIALOG_CYCVER               144
#define IDD_DIALOG_NEWMEASURE1          145
#define IDD_DIALOG_INIEDIT              145
#define IDD_EDENT                       146
#define IDD_MSGBOX                      147
#define IDB_BITMAP1                     148
#define IDB_IAEA_BITMAP                 148
#define IDR_TOOLBAR1                    149
#define IDB_BITMAP2                     150
#define IDB_CHECKBOXBMP                 150
#define IDD_XCAL                        151
#define IDD_MMMATCHDLG                  152
#define IDD_DIALOG4                     153
#define IDD_DIALOG5                     154
#define IDD_ABOUT1                      156
#define IDC_BUTTON1                     201
#define IDC_BUTTON2                     202
#define IDC_BUTTON3                     203
#define IDC_BUTTON4                     204
#define IDC_BUTTON5                     205
#define IDC_BUTTON6                     206
#define IDC_BUTTON7                     207
#define IDC_BUTTON8                     208
#define IDC_BUTTON9                     209
#define IDC_BUTTON0                     210
#define IDC_BUTTONDP                    211
#define IDC_BUTTONSIGN                  212
#define IDC_BUTTONONCE                  213
#define IDC_BUTTONCA                    214
#define IDC_EDIT                        215
#define IDC_BUTTONCE                    216
#define IDR_IMPEDIT                     217
#define IDC_STATIC_1                    1000
#define IDC_STATIC_2                    1001
#define IDC_STATIC_3                    1002
#define IDC_STATIC_4                    1003
#define IDC_STATIC_5                    1004
#define IDC_STATIC_6                    1005
#define IDC_STATIC_7                    1006
#define IDC_STATIC_8                    1007
#define IDC_STATIC_TEXT                 1008
#define IDC_STATIC_LABELPREV            1009
#define IDC_STATIC_LABELNEW             1010
#define IDC_STATIC_LABEL1               1011
#define IDC_STATIC_LABEL2               1012
#define IDC_STATIC_LABEL3               1013
#define IDC_STATIC_LABEL4               1014
#define IDC_STATIC_PREV1                1015
#define IDC_STATIC_PREV2                1016
#define IDC_STATIC_PREV3                1017
#define IDC_STATIC_PREV4                1018
#define IDC_STATIC_NEW1                 1019
#define IDC_STATIC_NEW2                 1020
#define IDC_STATIC_NEW3                 1021
#define IDC_STATIC_NEW4                 1022
#define IDC_STATIC_LABEL5               1023
#define IDC_LIST1                       1024
#define IDC_STATIC_PREV5                1025
#define IDC_ABORTOK                     1026
#define IDC_STATIC_NEW5                 1027
#define ID_EDIT_INIFILE                 1028
#define IDC_EM_FACILITY                 1030
#define IDC_EM_DETECTOR                 1031
#define IDC_EM_ID                       1032
#define IDC_EM_ENRICHMENT               1033
#define IDC_EM_BURNUP                   1034
#define IDC_EM_DISCHARGE_DATE           1036
#define IDC_EM_CYCLE                    1038
#define IDC_MSGBOX_NOTAGAIN             1039
#define IDC_MSGBOX_TEXT                 1040
#define IDC_EDENT_WARNING               1041
#define IDC_VERSION_LABEL               1043
#define IDC_CUSTOM1                     1044
#define IDC_LIST2                       1045
#define IDC_OLIST                       1045
#define IDC_TIMEPICKER                  1046
#define IDC_DATETIMEPICKER2             1049
#define IDC_DATEPICKER                  1049
#define ID_OK                           1050
#define ID_ANALYZE_IMP                  1051
#define IDC_MMMATCH                     1052
#define IDC_STATIC_ML                   1053
#define IDC_STATIC1                     1054
#define IDC_STATIC2                     1055
#define IDC_RICHEDIT21                  1056
#define IDC_LEGALESE                    1056
#define IDC_STATIC_WATCH                1213
#define IDC_EDIT_ACTIVITY               1216
#define IDC_STATIC_INSTRUCTION          1217
#define IDC_STATIC_COMMENT              1218
#define IDC_STATIC_INSTRUCTIONS         1219
#define IDC_EDIT_ACTIVITY2              1220
#define IDC_BUTTON1A                    1232
#define IDOKA                           1233
#define IDCANCELA                       1234
#define IDWATCH                         1235
#define IDC_GRAND_G1                    1236
#define IDC_GRAND_G2                    1237
#define IDC_GRAND_NA                    1238
#define IDC_GRAND_NB                    1240
#define IDC_GRAND_NC                    1241
#define IDC_GRAND_COUNTTIME             1245
#define IDC_STATIC_ASSM                 1254
#define IDC_PROGRESS1                   1289
#define IDC_PROGRESS2                   1290
#define IDC_MESSAGE                     1291
#define IDC_STATIC_DEVICELBL            1292
#define IDC_STATIC_DEVICEDATALBL        1293
#define IDC_IPEDIT                      1294
#define ID_BUTTON_BG                    3000
#define ID_BUTTON_ALLOTHER              3001
#define ID_BUTTON_AO_MEASURE            3500
#define ID_BUTTON_AO_IG                 3501
#define ID_BUTTON_AO_IS                 3502
#define ID_BUTTON_AO_AG                 3503
#define ID_BUTTON_AO_NB                 3504
#define ID_BUTTON_AO_GBUT               3505
#define ID_BUTTON_AO_NG                 3506
#define ID_BUTTON_AO_RETURN             3507
#define ID_BUTTON_VER_RETURN            4000
#define ID_BUTTON_VER_IR                4001
#define ID_BUTTON_VER_AV                4002
#define ID_BUTTON_VER_CV                4003
#define IDR_DMAINFRAME                  5999
#define IDB_RT_TITLE_BUTTONS            6101
#define IDB_SPLASH                      6102
#define IDD_RT_SPLASH                   6110
#define IDR_GENERITYPE                  6129
#define IDI_UPPER_LAYER_APP             6130
#define IDD_STARTUP_MSG_DLG             6131
#define IDD_GENERIC_EXIT_DLG            6147
#define IDD_RT_MIC_LOAD_INSPEC_INFO     6190
#define IDB_SEB_PRODUCT_SUPPORT_LANL_HEADER 6194
#define IDB_RT_TITLE_NIS5_DARK_1        6203
#define IDB_SEB_ABOUT_LANL              6206
#define IDD_SEB_IAEA_INSPECTION_ID_BOX  6207
#define IDC_INSTANT_MATCH_BTN           7000
#define IDC_APP_LIST_CB                 7001
#define IDC_SEB_ABOUT_UPPER_BAR         7027
#define IDC_SEB_ABOUT_LOWER_BAR_PLAIN   7028
#define IDC_SEB_ABOUT_MEMORY            7029
#define IDC_SEB_ABOUT_TITLE_BAR         7030
#define IDC_SEB_ABOUT_RESOURCES         7032
#define IDC_SEB_IAEA_INSPEC_REVIEW_NUMBER 7033
#define IDC_SEB_IAEA_INSPEC_REVIEW_START_DATE 7035
#define IDC_SEB_IAEA_INSPEC_REVIEW_END_DATE 7037
#define IDC_SEB_IAEA_INSPEC_REVIEW_START_TIME 7038
#define IDC_SEB_IAEA_INSPEC_REVIEW_DATE 7039
#define IDC_SEB_MODELESS_BOX_MESSAGE    7043
#define IDC_SEB_IAEA_INSPEC_REVIEW_TIME 7044
#define IDC_SEB_MODELESS_BOX_OK         7046
#define IDC_SEB_IAEA_INSPEC_REVIEW_END_TIME 7047
#define IDC_SEB_PS_CONTACT              7058
#define IDC_SEB_ABOUT_APP_NAME          7059
#define IDC_SEB_THREE_BOX_BUTTON_1      7061
#define IDC_RT_TITLE_CHANGE             7062
#define IDC_SEB_ABOUT_FACILITY          7063
#define IDC_SEB_IAEA_INSPEC_OK          7065
#define IDC_SEB_ABOUT_LOCATION          7066
#define IDC_SEB_IAEA_INSPEC_CANCEL      7068
#define IDC_SEB_THREE_BOX_BUTTON_2      7069
#define IDC_SEB_ABOUT_RT_VERSION        7070
#define IDC_SEB_THREE_BOX_BUTTON_3      7072
#define IDC_SEB_ABOUT_APP_VERSION       7073
#define IDC_SEB_IAEA_INSPEC_ID_LIST     7076
#define IDC_SEB_THREE_BOX_MESSAGE       7078
#define IDC_SEB_IAEA_INSPEC_DELETE      7080
#define IDC_SEB_IAEA_INSPEC_LOCATION    7082
#define IDC_SEB_PROGRESS_BAR_CANCEL     7083
#define IDC_SEB_IAEA_INSPEC_ID_ADD      7086
#define IDC_SEB_PROGRESS_BAR_MESSAGE    7087
#define IDC_EXIT_ALL_TOOLS_BTN          7096
#define IDC_EXIT_ONLY_THIS_TOOL_BTN     7097
#define IDC_EXIT_MESSAGE                7099
#define IDC_SEB_PASSWORD_REQUEST_MESSAGE 8027
#define IDC_SEB_PASSWORD_CHANGE_MESSAGE 8029
#define IDC_SEB_PASSWORD_CHANGE_PASSWORD1 8030
#define IDC_SEB_IAEA_INSPEC_FACILITY_NAME 8035
#define IDC_SPLASH_BITMAP               8036
#define IDC_RT_MIC_INSPEC_INFO_LIST     8037
#define IDC_SEB_IAEA_INSPEC_ID          8038
#define IDC_SEB_IAEA_INSPEC_ID_OK       8039
#define IDC_SEB_IAEA_INSPEC_ID_CANCEL   8040
#define IDC_RT_TITLE_EXIT_NOTIFY_FIX    8041
#define IDC_RT_START_TOOL_MESSAGE       8042
#define IDC_SEB_PASSWORD_REQUEST_PASSWORD 8044
#define IDC_SEB_PASSWORD_CHANGE_PASSWORD2 8045
#define IDC_SEB_IAEA_INSPEC_COMMENTS    8046
#define IDC_RT_TITLE_FACILITY_NAME      8047
#define IDC_RT_TITLE_REVIEW_DATE_TIME   8048
#define IDC_RT_TITLE_LOCATION           8049
#define IDC_RT_TITLE_INSPECTORS         8050
#define IDC_RT_TITLE_START_DATE_TIME    8051
#define IDC_RT_TITLE_END_DATE_TIME      8052
#define IDC_RT_TITLE_COMMENTS           8053
#define IDC_RT_TITLE_CONTINUE           8054
#define IDC_RT_TITLE_NEW                8055
#define IDC_RT_TITLE_EXIT               8056
#define IDC_RT_TITLE_PROMPT_FACILITY_NAME 8057
#define IDC_RT_TITLE_PROMPT_LOCATION    8058
#define IDC_RT_TITLE_PROMPT_INSPECTORS  8059
#define IDC_RT_TITLE_PROMPT_REVIEW_DATE 8060
#define IDC_RT_TITLE_REVIEW_NUMBER      8061
#define IDC_RT_TITLE_PROMPT_REVIEW_NUMBER 8062
#define IDC_RT_TITLE_PROMPT_END_DATE    8063
#define IDC_RT_TITLE_PROMPT_START_DATE  8064
#define IDC_RT_TITLE_PROMPT_REVIEW_PERIOD 8065
#define IDC_RT_TITLE_PROMPT_COMMENTS    8066
#define IDD_RT_TITLE                    8102
#define IDD_SEB_ABOUT_BOX               8104
#define IDD_RT_SPLASH1                  8105
#define IDD_SEB_PASSWORD_REQUEST_BOX    8106
#define IDD_SEB_PRODUCT_SUPPORT_BOX     8109
#define IDD_SEB_PASSWORD_CHANGE_BOX     8172
#define IDR_DBCSV                       8600
#define IDR_MPCSV                       8601
#define IDR_MSCSV                       8602
#define IDR_ULINI                       8603
#define IDR_APPINI                      8604
#define IDC_SEB_PROGRESS_BAR_BAR        14543
#define IDD_SEB_THREE_QUESTION_BOX_LARGE 21753
#define IDD_SEB_MODELESS_BOX_LARGE      21754
#define IDD_SEB_PROGRESS_BAR            23456
#define IDD_RT_START_TOOL               23457
#define IDD_SEB_IAEA_INSPECTION_BOX     23459
#define IDD_DIALOG_NEWMEASURE2          23460
#define IDD_DIALOG_IMPEDMEASURE         23460
#define IDD_STARTUP_MSG_IMP_DLG         23461
#define ID_TOOLMENUID                   32770
#define ID_TOOLCOMBOBOXID               32788
#define ID_TOOLCOMBOBOXGO               32789
#define ID_TOOLBAR_IMPORT               32799
#define ID_VIEW_PROCESSINGLOG           32800
#define ID_TOOLS                        32802
#define ID_TOOLS_IMPORT                 32810
#define ID_EDIT_BACKGROUNDCYCLES        33212
#define ID_EDIT_BACKGROUNDCYCLETIME     33262
#define ID_EDIT_DELTAENRICHMENT         33312
#define ID_EDIT_DELTACOOLINGTIME        33362
#define ID_EDIT_STANDARDMEASUREMENTCYCLES 33412
#define ID_EDIT_STANDARDMEASUREMENTCYCLETIME 33462
#define ID_EDIT_DETECTOR_ID             33512
#define ID_EDIT_RESETACKNOWLEDGEMENTS   33917
#define ID_EDIT_CONFIG_O_RAMA_C         33918
#define ID_EDIT_CONFIG_O_RAMA_D         33919
#define ID_EDIT_PING                    33920
#define ID_EDIT                         33921
#define ID_CANCELKEEP                   33922
#define SETTING_eBASEVALUE              34001
#define SETTING_eBGCYCLETIME            34001
#define SETTING_eBGCYCLES               34002
#define SETTING_eOFFSET_CNTRL           34003
#define SETTING_eOFFSET_CNTRL_REMOTE    34004
#define SETTING_eOFFSET_LIMIT_LOW       34005
#define SETTING_eOFFSET_LIMIT_HIGH      34006
#define SETTING_eOFFSET_TIME            34007
#define SETTING_eGAMMAGATE1             34008
#define SETTING_eGAMMAGATE2             34009
#define SETTING_eBAUD                   34010
#define SETTING_eDATABITS               34011
#define SETTING_eSTOPBITS               34012
#define SETTING_eTICKLE                 34013
#define SETTING_ePORT                   34014
#define SETTING_ePARITY                 34015
#define SETTING_eCYCLETIME              34016
#define SETTING_eMINSAMPLES             34017
#define SETTING_eMAXSAMPLES             34018
#define SETTING_eCOMMANDTIMEOUT         34019
#define SETTING_eICHVBIAS               34020
#define SETTING_eHVBIAS                 34021
#define SETTING_eCYCLES                 34022
#define SETTING_eMINIGRAND              34023
#define SETTING_eICBACKGROUND1          34024
#define SETTING_eICBACKGROUND2          34025
#define SETTING_eSCALE                  34026
#define SETTING_eMEASUREMENTS           34027
#define SETTING_eDATABASE               34028
#define SETTING_eMEASUREMENTPLAN        34029
#define SETTING_eDELTA_ENRICHMENT       34030
#define SETTING_eDELTA_COOLINGTIME      34031
#define SETTING_ePASSIVE_SYM            34032
#define SETTING_eACTIVITYLOG            34033
#define SETTING_eCOMMLOG                34034
#define SETTING_eLOGLOC                 34035
#define SETTING_eIRCONFIGLOC            34036
#define SETTING_eULINILOC               34037
#define SETTING_eULAPPSETTINGSLOC       34038
#define SETTING_eIRINILOC               34039
#define SETTING_eIRDATALOC              34040
#define SETTING_eIRCONFIGFILENAME       34041
#define SETTING_eULININAME              34042
#define SETTING_eULAPPSETTINGSNAME      34043
#define SETTING_eIRININAME              34044
#define SETTING_eIRDATAFILENAME         34045
#define SETTING_eMATCHDAYS              34046
#define SETTING_eMATCHMINUTES           34047
#define SETTING_eMATCHSECONDS           34048
#define SETTING_eFACILITYID             34049
#define SETTING_eDEMOVERSION            34050
#define SETTING_eBACKGROUND_A           34051
#define SETTING_eBACKGROUND_B           34052
#define SETTING_eBACKGROUND_C           34053
#define SETTING_eBACKGROUND_1           34054
#define SETTING_eBACKGROUND_2           34055
#define SETTING_eOFFSET_INTERNAL_CH0    34056
#define SETTING_eOFFSET_INTERNAL_CH1    34057
#define SETTING_eOFFSET_REMOTE_CH0      34058
#define SETTING_eOFFSET_REMOTE_CH1      34059
#define SETTING_eDETECTOR_ID            34060
#define SETTING_eBGCYCLES_CHOICE        34061
#define SETTING_eBGCYCLETIME_CHOICE     34062
#define SETTING_eCYCLES_CHOICE          34063
#define SETTING_eCYCLETIME_CHOICE       34064
#define SETTING_eDELTA_ENRICHMENT_CHOICE 34065
#define SETTING_eDELTA_COOLINGTIME_CHOICE 34066
#define SETTING_eDETECTOR_ID_CHOICE     34067
#define SETTING_eBGCYCLES_CHOICE_CONF   34068
#define SETTING_eBGCYCLETIME_CHOICE_CONF 34069
#define SETTING_eCYCLES_CHOICE_CONF     34070
#define SETTING_eCYCLETIME_CHOICE_CONF  34071
#define SETTING_eDELTA_ENRICHMENT_CHOICE_CONF 34072
#define SETTING_eDELTA_COOLINGTIME_CHOICE_CONF 34073
#define SETTING_eDETECTOR_ID_CHOICE_CONF 34074
#define SETTING_eININAMECOUNT           34075
#define ID_EDIT_BACKGROUNDCYCLES_U      34212
#define ID_EDIT_BACKGROUNDCYCLETIME_U   34262
#define ID_EDIT_DELTAENRICHMENT_U       34312
#define ID_EDIT_DELTACOOLINGTIME_U      34362
#define ID_EDIT_STANDARDMEASUREMENTCYCLES_U 34412
#define ID_EDIT_STANDARDMEASUREMENTCYCLETIME_U 34462

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
